### ISSUE TITLE
Remove header and footer from feedback portal

### ISSUE THREAD

**Issue by mrudhvika940** [vlead/feedback-portal#54]
Remove header and footer from feedback portal.

**Comment by travula** [comment]
Please keep the footer.  Create an iframe within a footer div and populate the src of the iframe from a config file.  Since feedback is using ginga templates, you can configure the footer service url. and use it to populate the template before it is served.

**Comment by ksripathi** [comment]
Resolved issue as stated @travula 
commit id : 1d858dbe6ed576df94e0d28833f20b1685613bbd
